/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORTS_H_RPCGEN
#define _AIRPORTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct kdTree {
	struct kdNode *root;
};
typedef struct kdTree kdTree;

struct kdNode {
	double *pos;
	int dir;
	struct airport *data;
	struct kdNode *left;
	struct kdNode *right;
};
typedef struct kdNode kdNode;

struct airport {
	char *code;
	char *name;
	double latitude;
	double longitude;
	double distance;
};
typedef struct airport airport;

struct placesArg {
	double latitude;
	double longitude;
};
typedef struct placesArg placesArg;

struct airportsLLNode {
	struct airport *airport;
	struct airportsLLNode *next;
};
typedef struct airportsLLNode airportsLLNode;

struct airportsRet {
	int err;
	union {
		airportsLLNode *airports;
	} airportsRet_u;
};
typedef struct airportsRet airportsRet;

#define AIRPORTS_PROG 0x38710268
#define AIRPORTS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define AIRPORTS_NEAR_COORD 1
extern  airportsRet * airports_near_coord_1(placesArg *, CLIENT *);
extern  airportsRet * airports_near_coord_1_svc(placesArg *, struct svc_req *);
extern int airports_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AIRPORTS_NEAR_COORD 1
extern  airportsRet * airports_near_coord_1();
extern  airportsRet * airports_near_coord_1_svc();
extern int airports_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_kdTree (XDR *, kdTree*);
extern  bool_t xdr_kdNode (XDR *, kdNode*);
extern  bool_t xdr_airport (XDR *, airport*);
extern  bool_t xdr_placesArg (XDR *, placesArg*);
extern  bool_t xdr_airportsLLNode (XDR *, airportsLLNode*);
extern  bool_t xdr_airportsRet (XDR *, airportsRet*);

#else /* K&R C */
extern bool_t xdr_kdTree ();
extern bool_t xdr_kdNode ();
extern bool_t xdr_airport ();
extern bool_t xdr_placesArg ();
extern bool_t xdr_airportsLLNode ();
extern bool_t xdr_airportsRet ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORTS_H_RPCGEN */
