/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "airports.h"

airportsLLNode * testLL();

airportsRet *
airports_near_coord_1_svc(placesArg *argp, struct svc_req *rqstp)
{
	static airportsRet result;

    // initialize server function
    // xdr_free((xdrproc_t)xdr_airportsRet, &result);
    result.err = 0;
    result.airportsRet_u.airports = NULL;

    // print payload from client
    printf("placesArg\n");
    printf("latitude: %0.2f   longitude: %0.2f\n", argp->latitude, argp->longitude);

    // return test payload
    result.airportsRet_u.airports = testLL();
	return &result;
}

airportsLLNode *
testLL() 
{
    airportsLLNode *LL = (airportsLLNode *)malloc(sizeof(airportsLLNode));
    airportsLLNode *curr = LL;
    for (int i = 0; i < 5; i++) {
        airport *newNode = (airport *)malloc(sizeof(airport));
        newNode->code = "code";
        newNode->name = "name";
        newNode->latitude = 3.14;
        newNode->longitude = 2.718;
        curr->airport = newNode;
        curr->next = (i == 4) ? NULL : (airportsLLNode *)malloc(sizeof(airportsLLNode));
        curr = curr->next;
    }
    return LL;
}


