/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"
#include "airports.h"
#include <limits.h>

#define NEW_STRUCT(s) (s *)malloc(sizeof(s))
#define NEW_STRING(s) (char *)malloc(strlen(s)+1)
#define CPY_STRING(dst, src) dst = NEW_STRING(src); strcpy(dst, src)
#define SUBSTR(src, dst, start, end) memcpy(dst, &src[start-1], end-start+1); dst[end-start+1] = '\0'

// function declarations
placesLLNode * testLL();

// function declarations for processing RPC call
airportsRet * findAirportsNearCoord(char *host, placesArg *coordinate);
CLIENT * connectToClient(char *host);
void checkIfResultIsNull(airportsRet *result, CLIENT *clnt);
airportsRet * createLocalCopy(airportsRet *result);
airport * copyAirport(airport *curr);
void disconnectFromClient(CLIENT *clnt, airportsRet *result);

// places server main function
placesRet *
airports_near_city_1_svc(clientArg *argp, struct svc_req *rqstp)
{
	static placesRet result;

    // initialize server function
    xdr_free((xdrproc_t)xdr_placesRet, &result);
    result.err = 0;

    // load places file
    char *placesFile = "data/places2k.txt";
    FILE *fp = fopen(placesFile, "r");
    if (fp == NULL) {
        printf("Could not open file %s\n", placesFile);
        exit(1);
    }

    // read lines
    char line[165], state[3], city[65], latitude[11], longitude[12];
    for (int i = 0; i < 5; i++) {
        printf("ROUND %d:\n", i);
        fgets(line, INT_MAX, fp);
        SUBSTR(line, state, 1, 2);
        SUBSTR(line, city, 10, 73);
        SUBSTR(line, latitude, 144, 153);
        SUBSTR(line, longitude, 154, 164);
        printf("    State: %s\n", state);
        printf("    City: %s\n", city);
        printf("    Latitude: %s\n", latitude);
        printf("    Longitude: %s\n", longitude);
    }

    // close file
    fclose(fp);

    // print payload from client
    printf("clientArg\n");
    printf("city: %s   state: %s\n", argp->city, argp->state);

    // test call airports server
    placesArg *coordinate = NEW_STRUCT(placesArg);
    coordinate->latitude = 6.28;
    coordinate->longitude = 0.5;
    airportsRet *airportsResult = findAirportsNearCoord("localhost", coordinate);

    // print airports result
    airportsLLNode *curr = (airportsResult->airportsRet_u).airports;
    while (curr != NULL) {
        printf("Code: %s  ", curr->airport->code);
        printf("Name: %s  ", curr->airport->name);
        printf("Latitude: %0.2f  ", curr->airport->latitude);
        printf("Longitude: %0.2f\n", curr->airport->longitude);
        curr = curr->next;
    }
    printf("\n\n");

    // TODO: dealloc linked list

    // return test result
    result.placesRet_u.airports = testLL();
	return &result;
}

placesLLNode *
testLL() 
{
    placesLLNode *LL = NEW_STRUCT(placesLLNode);
    placesLLNode *curr = LL;
    for (int i = 0; i < 5; i++) {
        airportInfo *newNode = NEW_STRUCT(airportInfo);
        newNode->code = "code";
        newNode->name = "name";
        newNode->distance = 3.14;
        curr->airport = newNode;
        curr->next = (i == 4) ? NULL : NEW_STRUCT(placesLLNode);
        curr = curr->next;
    }
    return LL;
}

airportsRet *
findAirportsNearCoord(char *host, placesArg *coordinate)
{
	CLIENT *clnt = connectToClient(host);
	airportsRet *result = airports_near_coord_1(coordinate, clnt);
    checkIfResultIsNull(result, clnt);
    airportsRet *resultCpy = createLocalCopy(result);
    disconnectFromClient(clnt, result);
    return resultCpy;
}

CLIENT *
connectToClient(char *host) 
{
    #ifndef	DEBUG
	CLIENT *clnt = clnt_create(host, AIRPORTS_PROG, AIRPORTS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit (1);
	}
    #endif	/* DEBUG */
}

void
checkIfResultIsNull(airportsRet *result, CLIENT *clnt) 
{
	if (result == (airportsRet *) NULL) {
		clnt_perror(clnt, "call failed");
	}
}

airportsRet *
createLocalCopy(airportsRet *result) 
{
    airportsRet *resultCpy = NEW_STRUCT(airportsRet);
    resultCpy->err = result->err;
    (resultCpy->airportsRet_u).airports = NEW_STRUCT(airportsLLNode);
    airportsLLNode *curr = (result->airportsRet_u).airports;
    airportsLLNode *cpy = (resultCpy->airportsRet_u).airports;
    for (; curr != NULL; curr = curr->next, cpy = cpy->next) {
        airport *newNode = copyAirport(curr->airport);
        cpy->airport = newNode;
        cpy->next = (curr->next == NULL) ? NULL : NEW_STRUCT(airportsLLNode);
    }
    return resultCpy;
}

airport *
copyAirport(airport *curr) 
{
    airport *newNode = NEW_STRUCT(airport);
    CPY_STRING(newNode->code, curr->code);
    CPY_STRING(newNode->name, curr->name);
    newNode->latitude = curr->latitude;
    newNode->longitude = curr->longitude;
    return newNode;
}

void
disconnectFromClient(CLIENT *clnt, airportsRet *result) 
{
    #ifndef	DEBUG
    clnt_freeres(clnt, (xdrproc_t)xdr_airportsRet, result);
	clnt_destroy(clnt);
    #endif	 /* DEBUG */
}
