/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "places.h"

bool_t
xdr_trie (XDR *xdrs, trie *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->root, sizeof (struct trieNode), (xdrproc_t) xdr_trieNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_trieNode (XDR *xdrs, trieNode *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->letter))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (trieNode), (xdrproc_t) xdr_trieNode))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->down, sizeof (trieNode), (xdrproc_t) xdr_trieNode))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->data, sizeof (struct location), (xdrproc_t) xdr_location))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->fullName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->state, ~0))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clientArg (XDR *xdrs, clientArg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->city, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->state, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportInfo (XDR *xdrs, airportInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->code, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distance))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placesLLNode (XDR *xdrs, placesLLNode *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->airport, sizeof (airportInfo), (xdrproc_t) xdr_airportInfo))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (placesLLNode), (xdrproc_t) xdr_placesLLNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placesRet (XDR *xdrs, placesRet *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_pointer (xdrs, (char **)&objp->placesRet_u.airports, sizeof (placesLLNode), (xdrproc_t) xdr_placesLLNode))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
